# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ani/Code/general/tempo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ani/Code/general/tempo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ani/Code/general/tempo/CMakeFiles /Users/ani/Code/general/tempo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ani/Code/general/tempo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tempo_lib

# Build rule for target.
tempo_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tempo_lib
.PHONY : tempo_lib

# fast build rule for target.
tempo_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_lib.dir/build.make CMakeFiles/tempo_lib.dir/build
.PHONY : tempo_lib/fast

#=============================================================================
# Target rules for targets named tempo_bench

# Build rule for target.
tempo_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tempo_bench
.PHONY : tempo_bench

# fast build rule for target.
tempo_bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_bench.dir/build.make CMakeFiles/tempo_bench.dir/build
.PHONY : tempo_bench/fast

examples/main.o: examples/main.cpp.o
.PHONY : examples/main.o

# target to build an object file
examples/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_bench.dir/build.make CMakeFiles/tempo_bench.dir/examples/main.cpp.o
.PHONY : examples/main.cpp.o

examples/main.i: examples/main.cpp.i
.PHONY : examples/main.i

# target to preprocess a source file
examples/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_bench.dir/build.make CMakeFiles/tempo_bench.dir/examples/main.cpp.i
.PHONY : examples/main.cpp.i

examples/main.s: examples/main.cpp.s
.PHONY : examples/main.s

# target to generate assembly for a file
examples/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_bench.dir/build.make CMakeFiles/tempo_bench.dir/examples/main.cpp.s
.PHONY : examples/main.cpp.s

src/tempo.o: src/tempo.cpp.o
.PHONY : src/tempo.o

# target to build an object file
src/tempo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_lib.dir/build.make CMakeFiles/tempo_lib.dir/src/tempo.cpp.o
.PHONY : src/tempo.cpp.o

src/tempo.i: src/tempo.cpp.i
.PHONY : src/tempo.i

# target to preprocess a source file
src/tempo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_lib.dir/build.make CMakeFiles/tempo_lib.dir/src/tempo.cpp.i
.PHONY : src/tempo.cpp.i

src/tempo.s: src/tempo.cpp.s
.PHONY : src/tempo.s

# target to generate assembly for a file
src/tempo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tempo_lib.dir/build.make CMakeFiles/tempo_lib.dir/src/tempo.cpp.s
.PHONY : src/tempo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tempo_bench"
	@echo "... tempo_lib"
	@echo "... examples/main.o"
	@echo "... examples/main.i"
	@echo "... examples/main.s"
	@echo "... src/tempo.o"
	@echo "... src/tempo.i"
	@echo "... src/tempo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

